#!/bin/bash

# echo "What's current name?"
# read INSTRING
echo "Rename output to what?"
read OUTSTRING

mv ${INSTRING}_out.e ${OUTSTRING}.e
mv ${INSTRING}_out.csv ${OUTSTRING}.csv
# mv log.txt log_${OUTSTRING}.txt
